services:
  app:
    environment:
      - NODE_ENV=development
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: data-generator-proj
    command: npm run dev
    ports:
      - 8080:8080
    